Add sqlite3 abstraction
Move xml helper functions to thirdparty/wi-libxml2


git-svn-id: file:///sources/wired/zanka-full-svn/trunk/libwired@8141 94223b32-352b-4d6d-a509-7b239cf53eea

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1270,6 +1270,7 @@ Optional Features:
   --enable-ssl            enable OpenSSL support
   --enable-iconv          enable iconv support
   --enable-libxml2        enable libxml2 support
+  --enable-sqlite3        enable sqlite3 support
   --enable-p7             enable P7 support
 
   --disable-largefile     omit support for large files
@@ -1727,6 +1728,9 @@ ac_config_headers="$ac_config_headers config.h"
 
 # Include shared macros
 # config.m4
+
+
+
 
 
 
@@ -3893,6 +3897,14 @@ fi
 
 
 
+# Check for sqlite3 support
+# Check whether --enable-sqlite3 was given.
+if test "${enable_sqlite3+set}" = set; then
+  enableval=$enable_sqlite3;
+fi
+
+
+
 # Check for P7 support
 # Check whether --enable-p7 was given.
 if test "${enable_p7+set}" = set; then
@@ -4270,7 +4282,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -4291,7 +4303,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -5290,6 +5302,18 @@ fi
 done
 
 
+
+	if test -z "$CPPFLAGS"; then
+		CPPFLAGS="-DWI_CORESERVICES"
+	else
+		MATCH=`expr -- "$CPPFLAGS" : ".*-DWI_CORESERVICES"`
+
+		if test "$MATCH" = "0"; then
+			CPPFLAGS="$CPPFLAGS -DWI_CORESERVICES"
+		fi
+	fi
+
+
 		wi_include_coreservices_framework_done="yes"
 	fi
 
@@ -5451,6 +5475,18 @@ _ACEOF
 fi
 
 done
+
+
+
+	if test -z "$CPPFLAGS"; then
+		CPPFLAGS="-DWI_CARBON"
+	else
+		MATCH=`expr -- "$CPPFLAGS" : ".*-DWI_CARBON"`
+
+		if test "$MATCH" = "0"; then
+			CPPFLAGS="$CPPFLAGS -DWI_CARBON"
+		fi
+	fi
 
 
 		wi_include_carbon_framework_done="yes"
@@ -8292,6 +8328,17 @@ fi
 
 
 	if test -z "$CPPFLAGS"; then
+		CPPFLAGS="-DWI_LIBXML2"
+	else
+		MATCH=`expr -- "$CPPFLAGS" : ".*-DWI_LIBXML2"`
+
+		if test "$MATCH" = "0"; then
+			CPPFLAGS="$CPPFLAGS -DWI_LIBXML2"
+		fi
+	fi
+
+
+	if test -z "$CPPFLAGS"; then
 		CPPFLAGS="-DWI_PLIST"
 	else
 		MATCH=`expr -- "$CPPFLAGS" : ".*-DWI_PLIST"`
@@ -8303,6 +8350,282 @@ fi
 
 
 		wi_include_libxml2_library_done="yes"
+	fi
+
+fi
+
+if test -n "$enable_sqlite3"; then
+
+	if test "$wi_include_sqlite3_library_done" != "yes"; then
+
+for ac_header in sqlite3.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  { echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------------- ##
+## Report this to axel@zankasoftware.com ##
+## ------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+else
+
+
+	{ { echo "$as_me:$LINENO: error: could not locate sqlite3
+
+If you installed sqlite3 into a non-standard directory, please run:
+
+    env CPPFLAGS=\"-I/path/to/include\" LDFLAGS=\"-L/path/to/lib\" ./configure" >&5
+echo "$as_me: error: could not locate sqlite3
+
+If you installed sqlite3 into a non-standard directory, please run:
+
+    env CPPFLAGS=\"-I/path/to/include\" LDFLAGS=\"-L/path/to/lib\" ./configure" >&2;}
+   { (exit 1); exit 1; }; }
+
+
+fi
+
+done
+
+
+		{ echo "$as_me:$LINENO: checking for sqlite3_open in -lsqlite3" >&5
+echo $ECHO_N "checking for sqlite3_open in -lsqlite3... $ECHO_C" >&6; }
+if test "${ac_cv_lib_sqlite3_sqlite3_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsqlite3  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char sqlite3_open ();
+int
+main ()
+{
+return sqlite3_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_sqlite3_sqlite3_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_sqlite3_sqlite3_open=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_sqlite3_sqlite3_open" >&5
+echo "${ECHO_T}$ac_cv_lib_sqlite3_sqlite3_open" >&6; }
+if test $ac_cv_lib_sqlite3_sqlite3_open = yes; then
+
+
+	if test -z "$LIBS"; then
+		LIBS="-lsqlite3"
+	else
+		MATCH=`expr -- "$LIBS" : ".*-lsqlite3"`
+
+		if test "$MATCH" = "0"; then
+			LIBS="$LIBS -lsqlite3"
+		fi
+	fi
+
+
+else
+
+
+	{ { echo "$as_me:$LINENO: error: could not locate sqlite3
+
+If you installed sqlite3 into a non-standard directory, please run:
+
+    env CPPFLAGS=\"-I/path/to/include\" LDFLAGS=\"-L/path/to/lib\" ./configure" >&5
+echo "$as_me: error: could not locate sqlite3
+
+If you installed sqlite3 into a non-standard directory, please run:
+
+    env CPPFLAGS=\"-I/path/to/include\" LDFLAGS=\"-L/path/to/lib\" ./configure" >&2;}
+   { (exit 1); exit 1; }; }
+
+
+fi
+
+
+
+	if test -z "$CPPFLAGS"; then
+		CPPFLAGS="-DWI_SQLITE3"
+	else
+		MATCH=`expr -- "$CPPFLAGS" : ".*-DWI_SQLITE3"`
+
+		if test "$MATCH" = "0"; then
+			CPPFLAGS="$CPPFLAGS -DWI_SQLITE3"
+		fi
+	fi
+
+
+		wi_include_sqlite3_library_done="yes"
 	fi
 
 fi
@@ -9486,6 +9809,17 @@ fi
 
 
 	if test -z "$CPPFLAGS"; then
+		CPPFLAGS="-DWI_LIBXML2"
+	else
+		MATCH=`expr -- "$CPPFLAGS" : ".*-DWI_LIBXML2"`
+
+		if test "$MATCH" = "0"; then
+			CPPFLAGS="$CPPFLAGS -DWI_LIBXML2"
+		fi
+	fi
+
+
+	if test -z "$CPPFLAGS"; then
 		CPPFLAGS="-DWI_PLIST"
 	else
 		MATCH=`expr -- "$CPPFLAGS" : ".*-DWI_PLIST"`
@@ -9755,6 +10089,18 @@ If you installed zlib into a non-standard directory, please run:
 
 
 fi
+
+
+
+	if test -z "$CPPFLAGS"; then
+		CPPFLAGS="-DWI_ZLIB"
+	else
+		MATCH=`expr -- "$CPPFLAGS" : ".*-DWI_ZLIB"`
+
+		if test "$MATCH" = "0"; then
+			CPPFLAGS="$CPPFLAGS -DWI_ZLIB"
+		fi
+	fi
 
 
 		wi_include_zlib_library_done="yes"
@@ -11089,7 +11435,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 ;;
 esac
-rm -f conftest*
+rm -f -r conftest*
   if test $ac_cv_sys_file_offset_bits = unknown; then
     { echo "$as_me:$LINENO: checking for _LARGE_FILES value needed for large files" >&5
 echo $ECHO_N "checking for _LARGE_FILES value needed for large files... $ECHO_C" >&6; }
@@ -11210,7 +11556,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 ;;
 esac
-rm -f conftest*
+rm -f -r conftest*
   fi
 fi
 
@@ -11455,7 +11801,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 ;;
 esac
-rm -f conftest*
+rm -f -r conftest*
 
 # We used to try defining _XOPEN_SOURCE=500 too, to work around a bug
 # in glibc 2.1.3, but that breaks too many other things.
